os: Visual Studio 2015
version: build{build}

branches:
  only:
  - master

environment:
  SpecFlowBaseVersion: 2.2.0
  SpecFlowPackageVersion: "2.2.0-ci$(APPVEYOR_BUILD_NUMBER)"
  
cache:
  - packages -> **\packages.config

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "$(SpecFlowBaseVersion)"
  assembly_file_version: "$(SpecFlowBaseVersion)"
  assembly_informational_version: "$(SpecFlowPackageVersion)"

nuget:
  project_feed: true
  disable_publish_on_pr: true

configuration: Release


build:
  project: TechTalk.SpecFlow.sln
  verbosity: normal

test:
  assemblies:
  - TechTalk.SpecFlow.GeneratorTests.dll
  - TechTalk.SpecFlow.RuntimeTests.dll
  - TechTalk.SpecFlow.IntegrationTests.dll
  - TechTalk.SpecFlow.Specs\bin\Release\TechTalk.SpecFlow.Specs.dll

artifacts:
- path: '\Installer\NuGetPackages\bin\SpecFlow.*.nupkg'
- path: Installer\SpecFlowBinPackage\bin\SpecFlowBinPackage.zip
- path: Installer\SpecFlowBinPackage\bin\SpecFlowSymbolPackage.zip