os: Visual Studio 2017
version: build{build}

branches:
  only:
  - master

environment:
  SpecFlowBaseVersion: 3.0.0
  SpecFlowPackageVersion: "3.0.0-ci$(APPVEYOR_BUILD_NUMBER)"
  
cache:
  - packages -> **\packages.config

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "$(SpecFlowBaseVersion)"
  assembly_file_version: "$(SpecFlowBaseVersion)"
  assembly_informational_version: "$(SpecFlowPackageVersion)"

nuget:
  project_feed: true
  disable_publish_on_pr: true

configuration: Debug

before_build:
- cmd: dotnet restore

build:
  project: TechTalk.SpecFlow.sln
  verbosity: normal



test_script:
- vstest.console /logger:Appveyor "Tests\TechTalk.SpecFlow.RuntimeTests\bin\Debug\net452\TechTalk.SpecFlow.RuntimeTests.dll" /TestAdapterPath:%USERPROFILE%\.nuget\packages\xunit.runner.visualstudio\2.2.0
- vstest.console /logger:Appveyor "Tests\TechTalk.SpecFlow.GeneratorTests\bin\Debug\net452\TechTalk.SpecFlow.GeneratorTests.dll"  /TestAdapterPath:%USERPROFILE%\.nuget\packages\xunit.runner.visualstudio\2.2.0
- vstest.console /logger:Appveyor "Tests\TechTalk.SpecFlow.Specs\bin\Debug\net452\TechTalk.SpecFlow.Specs.dll"  /TestAdapterPath:%USERPROFILE%\.nuget\packages\xunit.runner.visualstudio\2.2.0
- vstest.console /logger:Appveyor "Tests\TechTalk.SpecFlow.IntegrationTests\bin\Debug\net452\TechTalk.SpecFlow.IntegrationTests.dll"  /TestAdapterPath:%USERPROFILE%\.nuget\packages\xunit.runner.visualstudio\2.2.0


artifacts:
- path: '\Installer\NuGetPackages\bin\SpecFlow.*.nupkg'
